---

- name: teste de senha
  hosts: all
  gather_facts: false

  tasks:

    - name: Consultar PAM no AWX
      beyondtrust.password_safe.credentials: 
        url: "{{ beyondtrust_url }}"             
        client_id: "{{ beyondtrust_client }}"    
        client_secret: "{{ beyondtrust_secret }}"
        system_name: "{{ inventory_hostname }}"
        account_name: "svc-pam"
      register: pam_result
      delegate_to: localhost

    - name: Definir credenciais para o SSH
      ansible.builtin.set_fact:
        ansible_user: "svc-pam"
        ansible_password: "{{ pam_result.password }}"    
    
    - name: ping
      ansible.builtin.ping:

      
...