---

- name: teste de senha
  hosts: all
  gather_facts: false

  tasks:

    - name: Consultar PAM e definir credenciais
      ansible.builtin.set_fact:
        ansible_user: "svc-pam"
        ansible_password: "{{ lookup('beyondtrust.password_safe.credentials', url=beyondtrust_url, client_id=beyondtrust_client, client_secret=beyondtrust_secret, system_name=inventory_hostname, account_name='svc-pam') }}"  
    
    - name: ping
      ansible.builtin.ping:

      
...