---

- name: Testes de update
  hosts: all

  tasks:
    - name: Atualização de repo
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
      register: result

    - name: output
      debug:
        var: result

...